export const FETCH_PRODUCTS = "FETCH_PRODUCTS";
export const FETCH_PRODUCT_BY_ID = "FETCH_PRODUCT_BY_ID";
export const CLEAR_PRODUCT = "CLEAR_PRODUCT";
export const FETCH_TOTAL_BY_BRAND = "FETCH_TOTAL_BY_BRAND";
